name: LiteSpectator
main: me.Jonnyfant.LiteSpectator.LiteSpectator
author: Jonnyfant
version: 1.1
commands:
  spectate:
    permission: litespectator.use
    aliases: spec
permissions:
  litespectator.use:
    default: true